services:
  
  catalogue:
    build: ./catalogue-server
    container_name: catalogue-server
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: 172.15.10.20

  user-interaction:
    build: ./user-interaction
    container_name: user-interaction
    ports:
      - "9930:9930"
    depends_on: # used when a service is dependend on other services. 
      - catalogue
      - mqtt-mosquitto
    networks:
      app_net:
        ipv4_address: 172.15.10.100
   
  device-simulation:
    build: ./device-simulation
    container_name: device-simulation
    ports:
      - "5000:5000"
    depends_on: # used when a service is dependend on other services. 
      - catalogue
      - mqtt-mosquitto
    networks:
      app_net:
        ipv4_address: 172.15.10.3
 
  thingspeak:
    build: ./thingspeak/
    container_name: thingspeak
    ports:
      - "5001:5001"
    depends_on: # used when a service is dependend on other services. 
      - catalogue
      - mqtt-mosquitto
      - energy-price-api
    networks:
      app_net:
        ipv4_address: 172.15.10.60

  light-controller:
    build: ./light-controller/
    container_name: light-controller
    ports:
      - "9999:9999"
    depends_on: # used when a service is dependend on other services. 
      - catalogue
      - mqtt-mosquitto
      - energy-price-api
    networks:
      app_net:
        ipv4_address: 172.15.10.50



  energy-price-api:
    build: ./energy-price-api/
    container_name: energy-price-api
    ports:
      - "5003:9090"
    depends_on: # used when a service is dependend on other services. 
      - catalogue
      - mqtt-mosquitto
    networks:
      app_net:
        ipv4_address: 172.15.10.40
      # remember to set cherrypy.config.update({'server.socket_port': 9090}) in the module 
      # in order to make it work 
  
  
  
  mqtt-mosquitto:
    build: ./mqtt-broker/
    container_name: mosquitto-broker
    ports: 
      - "1883:1883"
    networks:
      app_net:
        ipv4_address: 172.15.10.5
  

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.15.10.0/24"
        - subnet: "2001:3984:3989::/64"
